// <auto-generated />
using System;
using Hoard.Data.Persistence.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hoard.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HoardDbContext))]
    partial class HoardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Hoard.Core.Entities.Game.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PlatformID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.HasIndex("PlatformID");

                    b.HasIndex("Title", "PlatformID", "ReleaseDate")
                        .IsUnique();

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PlatformID = 1,
                            ReleaseDate = new DateTime(2015, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Legend of Heroes: Trails in the Sky FC Evolution"
                        },
                        new
                        {
                            ID = 2,
                            PlatformID = 2,
                            ReleaseDate = new DateTime(2018, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Monster Hunter World"
                        },
                        new
                        {
                            ID = 3,
                            PlatformID = 3,
                            ReleaseDate = new DateTime(2015, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Yoshi's Woolly World"
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.GameGenre", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("GameID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameID = 1,
                            GenreID = 1
                        },
                        new
                        {
                            GameID = 1,
                            GenreID = 4
                        },
                        new
                        {
                            GameID = 2,
                            GenreID = 2
                        },
                        new
                        {
                            GameID = 3,
                            GenreID = 3
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Turn-based RPG"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Action RPG"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Platform"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Visual novel"
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Platform", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Sony Playstation Vita"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Steam"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nintendo Switch"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Nintendo 3DS"
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.PlayData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Dropped")
                        .HasColumnType("bit");

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("GameID", "PlayerID")
                        .IsUnique();

                    b.ToTable("PlayData");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Dropped = false,
                            GameID = 1,
                            PlayerID = 1
                        },
                        new
                        {
                            ID = 2,
                            Dropped = true,
                            GameID = 1,
                            PlayerID = 2
                        },
                        new
                        {
                            ID = 3,
                            Dropped = false,
                            GameID = 2,
                            PlayerID = 1
                        },
                        new
                        {
                            ID = 4,
                            Dropped = false,
                            GameID = 2,
                            PlayerID = 2
                        },
                        new
                        {
                            ID = 5,
                            Dropped = false,
                            GameID = 3,
                            PlayerID = 1
                        },
                        new
                        {
                            ID = 6,
                            Dropped = true,
                            GameID = 3,
                            PlayerID = 2
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.PlayStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrdinalNumber")
                        .IsUnique();

                    b.ToTable("PlayStatuses");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Playing",
                            OrdinalNumber = 1
                        },
                        new
                        {
                            ID = 2,
                            Name = "Hiatus",
                            OrdinalNumber = 2
                        },
                        new
                        {
                            ID = 3,
                            Name = "Finished",
                            OrdinalNumber = 3
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dropped",
                            OrdinalNumber = 4
                        },
                        new
                        {
                            ID = 5,
                            Name = "Endless",
                            OrdinalNumber = 5
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Meintje"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Bram"
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Playthrough", b =>
                {
                    b.Property<int>("PlayDataID")
                        .HasColumnType("int");

                    b.Property<int>("OrdinalNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayStatusID")
                        .HasColumnType("int");

                    b.Property<int>("PlaytimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("SideContentCompleted")
                        .HasColumnType("bit");

                    b.HasKey("PlayDataID", "OrdinalNumber");

                    b.HasIndex("PlayStatusID");

                    b.ToTable("Playthroughs");

                    b.HasData(
                        new
                        {
                            PlayDataID = 1,
                            OrdinalNumber = 1,
                            DateEnd = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            DateStart = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            PlayStatusID = 1,
                            PlaytimeMinutes = 3000,
                            SideContentCompleted = false
                        },
                        new
                        {
                            PlayDataID = 3,
                            OrdinalNumber = 1,
                            PlayStatusID = 3,
                            PlaytimeMinutes = 30000,
                            SideContentCompleted = false
                        },
                        new
                        {
                            PlayDataID = 4,
                            OrdinalNumber = 1,
                            DateEnd = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            DateStart = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            PlayStatusID = 1,
                            PlaytimeMinutes = 29000,
                            SideContentCompleted = false
                        },
                        new
                        {
                            PlayDataID = 5,
                            OrdinalNumber = 1,
                            DateEnd = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            DateStart = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            PlayStatusID = 2,
                            PlaytimeMinutes = 1000,
                            SideContentCompleted = true
                        },
                        new
                        {
                            PlayDataID = 5,
                            OrdinalNumber = 2,
                            DateEnd = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            DateStart = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            PlayStatusID = 1,
                            PlaytimeMinutes = 500,
                            SideContentCompleted = false
                        },
                        new
                        {
                            PlayDataID = 6,
                            OrdinalNumber = 1,
                            DateEnd = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            DateStart = new DateTime(2021, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            PlayStatusID = 4,
                            PlaytimeMinutes = 10,
                            SideContentCompleted = false
                        });
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Game", b =>
                {
                    b.HasOne("Hoard.Core.Entities.Game.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.GameGenre", b =>
                {
                    b.HasOne("Hoard.Core.Entities.Game.Game", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Entities.Game.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.PlayData", b =>
                {
                    b.HasOne("Hoard.Core.Entities.Game.Game", "Game")
                        .WithMany("PlayData")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Entities.Game.Player", "Player")
                        .WithMany("GameProgress")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Playthrough", b =>
                {
                    b.HasOne("Hoard.Core.Entities.Game.PlayData", "PlayData")
                        .WithMany("Playthroughs")
                        .HasForeignKey("PlayDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hoard.Core.Entities.Game.PlayStatus", "PlayStatus")
                        .WithMany()
                        .HasForeignKey("PlayStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayData");

                    b.Navigation("PlayStatus");
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Game", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("PlayData");
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.PlayData", b =>
                {
                    b.Navigation("Playthroughs");
                });

            modelBuilder.Entity("Hoard.Core.Entities.Game.Player", b =>
                {
                    b.Navigation("GameProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
